apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "etcd-operator.name" . }}
  namespace: {{ .Values.global.namespace }}
  annotations: {{ include "global.annotations.standard" . | indent 4 }}
  labels:
    name: {{ include "etcd-operator.name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "etcd-operator.name" . }}
    spec:
      containers:
      - name: {{ include "etcd-operator.name" . }}
        image: quay.io/coreos/etcd-operator:v0.8.3
        command:
        - etcd-operator
        - "--create-crd=false"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: etcd-backup-operator
        image: quay.io/coreos/etcd-operator:v0.8.3
        command:
        - etcd-backup-operator
        - "--create-crd=false"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: etcd-restore-operator
        image: quay.io/coreos/etcd-operator:v0.8.3
        command:
        - etcd-restore-operator
        - "--create-crd=false"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
